-- Schema inferred from SQL queries in src/repos and src/controllers.
-- Run against the `sastacoupon` database.

CREATE TABLE IF NOT EXISTS ADDRESS (
  ID       INT AUTO_INCREMENT PRIMARY KEY,
  STREET   VARCHAR(255) NULL,
  CITY     VARCHAR(120) NULL,
  STATE    VARCHAR(120) NULL,
  COUNTRY  VARCHAR(120) NULL,
  ZIPCODE  VARCHAR(20)  NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COUPON_IMAGE (
  ID            INT AUTO_INCREMENT PRIMARY KEY,
  URL           MEDIUMTEXT   NULL,
  OCCASION      VARCHAR(120)  NULL,
  DAFAULT_IMAGE TINYINT(1)    NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Migration (run once on existing DB):
-- ALTER TABLE COUPON_IMAGE MODIFY URL MEDIUMTEXT;

CREATE TABLE IF NOT EXISTS USERS (
  ID            INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL_ID      VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD      VARCHAR(255) NOT NULL,
  ADDRESS_ID    INT          NULL,
  FIRST_NAME    VARCHAR(120) NULL,
  LAST_NAME     VARCHAR(120) NULL,
  CONTACT       VARCHAR(30)  NULL,
  PROFILE_IMG   VARCHAR(1024) NULL,
  WALLET_AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0,
  CONSTRAINT FK_USERS_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COUPON (
  ID                INT AUTO_INCREMENT PRIMARY KEY,
  NAME              VARCHAR(255) NOT NULL,
  DESCRIPTION       TEXT         NULL,
  EXPIRY            DATE         NULL,
  PRICE             DECIMAL(10,2) NOT NULL DEFAULT 0,
  SELLER_ID         INT          NULL,
  BUYER_ID          INT          NULL,
  IMAGE_ID          INT          NULL,
  COUPON_CODE       VARCHAR(255) NULL,
  SOLD              TINYINT(1)   NOT NULL DEFAULT 0,
  CREATED_TIMESTAMP TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_COUPON_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_COUPON_BUYER  FOREIGN KEY (BUYER_ID)  REFERENCES USERS(ID),
  CONSTRAINT FK_COUPON_IMAGE  FOREIGN KEY (IMAGE_ID)  REFERENCES COUPON_IMAGE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
  ORDER_ID          VARCHAR(64) PRIMARY KEY,
  COUPON_ID         INT          NULL,
  STATUS            VARCHAR(50)  NULL,
  BUYER_ID          INT          NULL,
  SELLER_ID         INT          NULL,
  TRANSACTION_TYPE  VARCHAR(50)  NULL,
  PAYMENT_ID        VARCHAR(64)  NULL,
  PAYMENT_TIMESTAMP TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_ORDER_COUPON FOREIGN KEY (COUPON_ID) REFERENCES COUPON(ID),
  CONSTRAINT FK_ORDER_BUYER  FOREIGN KEY (BUYER_ID)  REFERENCES USERS(ID),
  CONSTRAINT FK_ORDER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CONTACT_US (
  ID       INT AUTO_INCREMENT PRIMARY KEY,
  NAME     VARCHAR(120) NULL,
  EMAIL    VARCHAR(255) NULL,
  ORDER_ID VARCHAR(64)  NULL,
  MESSAGE  TEXT         NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
